version: 2.1

orbs:
  docker: circleci/docker@1.5.0

jobs:
  init:
    docker:
      - image: python:3.7.3-stretch
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "hello_app/requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: |
            python3 -m venv .devops-capstone
            source .devops-capstone/bin/activate
            make install
      - save_cache:
          paths:
            - ./.devops-capstone
          key: v1-dependencies-{{ checksum "hello_app/requirements.txt" }}
      - run:
          name: Run lint
          command: |
            source .devops-capstone/bin/activate
            make lint 

#TODO1: job for smoke tests for "bare" app
#TODO2: job for smoke tests for "containerized" app

workflows:
  default:
    jobs:
      - init
      - docker/publish: # Set env variables: DOCKER_LOGIN and DOCKER_PASSWORD
          image: $DOCKER_LOGIN/hello-app
          path: hello_app
          docker-context: hello_app
          deploy: true
          # tag: '1.0-${CIRCLE_SHA1:0:7}'
          tag: 'latest'
          update-description: true          
          requires: [init]
